version: 0.2

env:
  variables:
    ENVIRONMENT: dev
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - python3 -m venv /root/venv
      - . /root/venv/bin/activate
      - pip install --upgrade pip
      # - pip3 install pytest && pip3 install poetry
      - pip3 install poetry
      - poetry install
      - yarn install
      - yarn global add serverless
  build:
    commands:
      - sls deploy
      # - echo Running tests
      # - pytest -s
cache:
  paths:
    - '/node_modules/**/*'
    - '/root/venv/**/*'
    - '/root/.cache/pip/**/*'
    - '/root/.cache/pypoetry/virtualenvs/**/*'
