# serverless.yml

service: reddit-finance-webscrapper

provider:
  name: aws
  runtime: python3.8

functions:
  scrapper:
    handler: handler.main

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
